<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="classes_utils_tests.py" name="classes_utils_tests.Test-20190510180804" skipped="0" tests="1" time="0.009" timestamp="2019-05-10T18:08:04">
	<testcase classname="classes_utils_tests.Test" file="unittests\classes_utils_tests.py" line="24" name="test_md5" time="0.009" timestamp="2019-05-10T18:08:04">
		<failure message="'827ccb0eea8a706c4c34a16891f84e7b' != 'sdf'
- 827ccb0eea8a706c4c34a16891f84e7b
+ sdf
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "c:\users\mathe\documents\shared\github\eswqa\unittests\classes_utils_tests.py", line 26, in test_md5
    self.assertEqual(md5, "sdf")
AssertionError: '827ccb0eea8a706c4c34a16891f84e7b' != 'sdf'
- 827ccb0eea8a706c4c34a16891f84e7b
+ sdf

]]>		</failure>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
