<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="classes_utils_tests.py" name="classes_utils_tests.Test-20190510175328" skipped="0" tests="1" time="0.012" timestamp="2019-05-10T17:53:28">
	<testcase classname="classes_utils_tests.Test" file="unittests\classes_utils_tests.py" line="8" name="test_md5" time="0.012" timestamp="2019-05-10T17:53:28">
		<error message="module 'classes.utils' has no attribute 'md5'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "c:\users\mathe\documents\shared\github\eswqa\unittests\classes_utils_tests.py", line 9, in test_md5
    md5 = Utils.md5("12345")
AttributeError: module 'classes.utils' has no attribute 'md5'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
